### ISSUE TITLE
Highlight region overlap

### ISSUE THREAD

**Issue by ahirschberg** [ahirschberg/code_steps#10]
Because html is used to define the highlight regions used in the lessons code viewer, allowing for overlapping highlight regions is fairly difficult. For example, if you had something like:

``` java
//~  |    regiona     |
//~               |          regionb     |
     System.out.println("Some code here");
```

(assuming that the parser could recognize multiple lines of region directives, which it currently can't :stuck_out_tongue:)

How should this render to html?
Would this feature be used frequently enough to warrant adding support for it?

**Comment by jelkner** [comment]
Given the limited resources (your time and effort) and the most important goal of the project - to help you (and now me) present CS lessons to our students - an agile approach is the one that makes the most sense to me.  Given the high cost of this feature and the lack of any clear cut use cases, I would argue it is not a priority at this stage.
