### ISSUE TITLE
Setup instructions in readme are incomplete

### ISSUE THREAD

**Issue by ahirschberg** [ahirschberg/code_steps#12]
In order to allow people to develop lessons for the app without needing the dart sdk installed, the readme recommends to use the `gh-pages` branch instead.

While the gh-pages branch does have a compiled-to-js version of the app, it doesn't have the build_json.rb script or the Makefile. The folder structure is also slightly different, so even if these files were copied over to that branch, the script wouldn't place the lessons where the app is expecting them.

Should the script and Makefile just be copied over to the gh-pages branch, or is there a more elegant solution?

Related to #11

**Comment by ahirschberg** [comment]
Possible solution would be to add a post-commit hook to master that updates gh-pages with the proper files. [Example](http://stackoverflow.com/a/23985451)

**Comment by ahirschberg** [comment]
Continuous integration now handled via codeship! The `gh-pages` branch should automatically stay in sync with master.

**Comment by richardscollin** [comment]
You should add a link to the github pages site from the readme in master. Currently I can't figure out how I'm supposed to get started using this from just looking at the readme.
