### ISSUE TITLE
Add GUI editor for creating lessons

### ISSUE THREAD

**Issue by ahirschberg** [ahirschberg/code_steps#8]
Would make developing content easier and more accessible, since learning a new markup language wouldn't be necessary. The editor would generate json files to be loaded into the app for users to interact with.

**Comment by jelkner** [comment]
Could be fine as a long as it doesn't replace the ability to use markdown, which I actually prefer to a GUI.  I want to edit in vim, and I want the conceptual freedom that using markup rather than a WYSIWYG tool gives me.

**Comment by ahirschberg** [comment]
If I were to implement a gui, it would definitely still use markdown as the format for developing steps. 

I think that a gui would be more accessible to the average CS enthusiast wanting to write lessons, although I personally would still prefer the terminal. It would be nice to develop both options in parallel.

**Comment by ahirschberg** [comment]
After looking at the current method of authoring lessons, I think developing a GUI editor should be a high priority. The current text editor system locks an author in to doing things per-line. This could be an issue if an author wants to have an entire section of code hide and show, for example. 

In addition, with each new command added as an option for modifying the display of the code in a lesson, the author has to memorize more and more keywords. With a gui, all this overhead would go away.

Downsides:
- Harder to use an editor of choice
- could be hard to develop a GUI that's usable, especially with time constraints
- would have to abandon or rework the current `build_json.rb` pipeline for lesson generation

@jelkner thoughts?

**Comment by ahirschberg** [comment]
Editor is now in a working state, although it is still very rough around the edges. Closing this issue as too general
